### ISSUE TITLE
XMLLINT problem on Mac

### ISSUE THREAD

**Issue by calebeaires** [NathanaelA/nativescript-liveedit#1]
XMLLINT has not been detected, disabled XMLLINT support.

**Comment by calebeaires** [comment]
it works after changed the line 87 to

cp.exec("xmllint --noout platforms/android/AndroidManifest.xml", {timeout: 3000}, _xmllintCallback);

**Comment by NathanaelA** [comment]
Yep, the minute I read your error, I realized my over sight on the check that I added as a last minute item to eliminate tech support.       I've already pushed v0.0.2 which has a check for the platform and adds the hash bang to it so you can run it alone.   :grin:
