### ISSUE TITLE
Error with compiled Typescript code

### ISSUE THREAD

**Issue by GitCharm** [NathanaelA/nativescript-liveedit#10]
LiveEdit is great - just getting the following error though:

Watching your project: com.xxxxx.com
Found 2:  change ./app/views/appointments/appointments-view-model.js 14490237830
16 Wed Dec 02 2015 12:36:23 GMT+1000 (E. Australia Standard Time) 1449023783016
6806
## Checking updated file:  ./app/views/appointments/appointments-view-model.js

---
## ---- Failed Sanity Tests on ./app/views/appointments/appointments-view-model.js

---

STDOut: ./app/views/appointments/appointments-view-model.js: line 3, col 5, Rede
finition of '__extends'.
./app/views/appointments/appointments-view-model.js: line 3, col 17, Possible st
rict violation.
./app/views/appointments/appointments-view-model.js: line 5, col 21, Possible st
rict violation.

3 errors

I've based my view models on the way the sample Friends app is coded (which is the compiled typescript code):

1  'use strict';
2  
3  var __extends = this.__extends || function (d, b) {
4  for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
5    function __() { this.constructor = d; }
6    __.prototype = b.prototype;
7    d.prototype = new __();
8  };

Hope this can be fixed.

Many thanks
Janine

**Comment by NathanaelA** [comment]
Uhm, did you copy lines 3-8 or were they generated?   My understanding is that block of code is not used anymore and just a waste of space.  (And they cause a "use strict" violation, which is what jshint is telling you about).  If you delete 3-8 in that file; you should be good to go.

**Comment by GitCharm** [comment]
Hi -I based my code around the Nativescript Friends app - so copied the view model design from their.

Deleting has worked a treat!  - Many thanks - I just love your LiveEdit!

Janine
