### ISSUE TITLE
Camel Case Expectation

### ISSUE THREAD

**Issue by philvbprogrammer** [NathanaelA/nativescript-liveedit#16]
the Identifier 'time_diff' is not in camel case., Unfortunately the time_diff is a json attribute from a webservice I have no control of., is this checking really needed?
## Checking updated file:  ./app/shared/device-list-view-model.js

---
## ---- Failed Sanity Tests on ./app/shared/device-list-view-model.js

---

STDOut: ./app/shared/device-list-view-model.js: line 45, col undefined, Identifi
er 'time_diff' is not in camel case.
./app/shared/device-list-view-model.js: line 45, col undefined, Identifier 'time
_diff' is not in camel case.

2 errors

**Comment by NathanaelA** [comment]
You can edit the ,jshintrc file and turn off that check.    You can also disable it in a specific file by using the /*jshint camelcase: true */ in the header.

**Comment by philvbprogrammer** [comment]
Excellent !!! thanks Nathanael, Keep up the good work, really like this add-on :+1: 
and for historical expansion.
the .jshintrc file is in your nativescript project folder
the jshint camelcase: true should be jshint camelcase: false to turn off the check.
Thanks
Phil
