### ISSUE TITLE
package.json' does not exist?

### ISSUE THREAD

**Issue by Daxito** [NathanaelA/nativescript-liveedit#17]
I keep getting this error when running node watcher, any idea? why is it searching for this file under app folder?

$ node watcher

---

NativeScript LiveEdit Watcher v0.13
## (c)2015, 2016, Master Technology.  www.master-technology.com

Watching your project: com.abc.yxz
remote object '/data/data/com.abc.yxz/files/./app/package.json' does not exist
Error: remote object '/data/data/com.abc.yxz/files/./app/package.json' does not exist
 86

**Comment by NathanaelA** [comment]
Have you done a "tns run android" or "tns run android --emulator" first to install the app on the device.  The app needs to be installed at least once before liveedit can do anything.

Also Is this a real device or a emulator?

**Comment by Daxito** [comment]
Yes, the app was running after a tns run android, then I opened another terminal and navigated to the root folder of the app and tried to run the npm whatcher,  or should I do this:
1. Tns run android 
2. Ctrl C
3. Npm whatcher 
?

Maybe I should try that, I had to uninstall the plugin so right now I cannot tell if that works.

**Comment by NathanaelA** [comment]
After you do a **tns run android** the app actually starts up correct?
Then you can either cancel the run command; or you can open another console and then start the watcher.

**Comment by Daxito** [comment]
Well, seems like it works with a brand new app, kind of, with the brand new app it syncs css, xml and "code-behind", but not ViewModel changes, until I make a modification to the code-behind then it reflects the VM code changes.

For my existing App, it does not work at all, I see this message:

Checking updated file:  ./app/views/login/lo.xml
Pushed to Device:  ./app/views/login/lo.xml /data/local/tmp/com.abc.abc/views%2Flogin%2Flo%2Exml

But never see the xml changes (just a label with different text)... I guess I need to isolate the problem with this existing app, something is making noise to your plugin I think.

Also, I see the error "...package.json' does not exist..." on both apps, the new one and the existing one, maybe this error does not matter...

**Comment by NathanaelA** [comment]
Daxito,

  If you want it to show Modal changes; you have to tell LiveEdit about which page the modal belongs to by using the **addModelPageLink(Page, Model)** command.  Otherwise it reloads the modal; but because the page never resets you don't see the changes.

As for your packages.json issue; is this a real device or on a emulator?

**Comment by Daxito** [comment]
Go it, ok, well, then it works, but I just see that harmless  message about the package.json, it is a real device, I guess we can close this ticket then, we can reopen if needed.
