### ISSUE TITLE
No changes detected

### ISSUE THREAD

**Issue by calebeaires** [NathanaelA/nativescript-liveedit#2]
node watcher.js works great, but changes dont works on a Geny Virtual device. (LiveSync Watcher v0.02)

Checking updated file:  ./app/main-page.xml
Pushing to Device:  ./app/main-page.xml

**Comment by NathanaelA** [comment]
1. Does your adb log show any errors on the Geny Virtual Machine?
2. Did you compile your own Android-runtime and use my patch https://github.com/NativeScript/android-runtime/pull/92 -- without this patch, the Android side won't be able to reload the files.

**Comment by calebeaires** [comment]
adb log dont has errors related to it. But I didnt use your android-runtime. I am not a power user to do that. Could you give a clue how to proceed!?

**Comment by NathanaelA** [comment]
One option is I could distribute my runtime that I compiled...    Then you would just download the runtime and do a
 **tns platform remove android** 
and then
**tns platform add android --frameworkPath=<downloadedRuntimeName>**

If you want to build the runtime yourself; you can follow the instructions at https://github.com/NativeScript/android-runtime and get the things you need installed and then build it.

**Comment by calebeaires** [comment]
Distribute tour runtime will be great :)

**Comment by emiloberg** [comment]
Yeah, that'd be great for us non-eclipsers!

**Comment by NathanaelA** [comment]
I have uploaded my runtimes.  See the main https://github.com/Nathanaela/nativescript-livesync/blob/master/README.md instructions.  

(I also don't use eclipse -- I do all my compiling from the command line)

**Comment by NathanaelA** [comment]
I have spent some time getting ready for the new plugin interface.  Once you have the new TNS v1.1.3 command line (which should be released very, very, very shortly) -- you can do `tns plugin add nativescript-livesync` and it will take care of everything including installing the replacement runtimes.   

The current version I just uploaded has v1.1.0 runtimes, in case their are people who are going to stay on the v1.1.0 android runtimes.     But I have already compiled the v1.2.0 runtimes (as they have tagged them as v1.2.0 already) and just waiting for Telerik to pull the trigger on actually releasing v1.2.0 in the next day or so.

**Comment by calebeaires** [comment]
That`s cool. I expect NativeScript goes ready to the "production time" very soon! Have you take a look at Tabris.js? https://tabrisjs.com/

**Comment by NathanaelA** [comment]
Tabris-JS is an interesting project, I hadn't seen it before; but it does not seem to be nearly as well thought out as NativeScript.   It does have a couple things going for it; but based on reading through several of its repos; I will definitely don't think it is prime time either...
