### ISSUE TITLE
node watcher not working

### ISSUE THREAD

**Issue by shripalsoni04** [NathanaelA/nativescript-liveedit#4]
I created a new nativescript project and added android platform to it. 
(nativescript cli version : 1.2.0, machine: MacBook)

Then I installed nativescript-livesync plugin using 
**tns plugin add nativescript-livesync**

Now, when I start the watcher using,
node watcher

It is giving me following error:
**Your platform does not seem to be running the correct version of the runtimes.  Please see http://github.com/NathanaelA/nativescript-livesync**

To make it working, I changed the code of watcher.js at line 68, 69 to update the hash value.
`checkFileSha("./platforms/android/libs/x86/libNativeScript.so","405170e1b37558bd87ab37274e623a195391ac7f");`
`checkFileSha("./platforms/android/libs/armeabi-v7a/libNativeScript.so","9b42b4c7c8d891f344b83d4e1c44db6d43bff60b");`

Can you please verify this.

Can you add a note in **Usage & Running** section of **README.md** file, that we need to trigger 
**node watcher** to start the watcher. As it is missing in the description.

**Comment by NathanaelA** [comment]
Hmmm, that is weird -- the runtime hashes that I used were all from the release version.  I'll re-pull v1.20 of the runtimes just to check on my end.   

 If you check your main package.json file at the root of your project; what does it say for "tns-android" -> "version"

**Comment by shripalsoni04** [comment]
In package.json which is at root of my project,
`"tns-android": {
      "version": "1.2.0"
    }`

**Comment by NathanaelA** [comment]
My brain was for some reason not comprehending what you wrote.   You are correct, the watcher itself has the wrong file hashes.    I'll get that fixed and pushed today.  Thanks!

**Comment by NathanaelA** [comment]
Erps, forgot to say this was fixed back on Aug 4th and close this issue...
