### ISSUE TITLE
Optional JSHint Support For Typescript

### ISSUE THREAD

**Issue by shripalsoni04** [NathanaelA/nativescript-liveedit#5]
I have installed jshint in my machine.

I am using typescript to create nativescript project.

The compiled code of typescript is not compliant with jsHint. And due to that, watcher is getting stopped working.

Can we have an option to disable jsHint in such scenarios or any better solution?

**Comment by NathanaelA** [comment]
Ah, I never checked on actual TypeScript support.    Do you have any tool that is automatically converting the TypeScript into JavaScript when you save it; or do you need the Watcher to do so.    Right now the watcher ignores .ts files it only watches .xml, .css, and .js files.
The devices & emulators needs JavaScript; so unless you are auto-converting them somehow in your app folder; the watcher won't see it.   But it would be easy to add auto TS -> JS support to the watcher so it would pick up TS file changes and then compile them.

**Comment by shripalsoni04** [comment]
I am using **gulp-typescript** to convert TS->JS. 

I have setup the build system in my IDE: Visual Studio Code to call task to compile Typescript file.

On compile of the typescript file, it will create/update javascript file and on change of such javascript files, the watcher will trigger and it will run JSHint command.

Now, as the javascript file is automatically created by typescript compiler, it has some code, which is not compliant with JSHint. So watcher is getting stopped due to that errors.

For now, I am passing --disableJSHint flag while running command,
**node watcher --disableJSHint**
And have done below modification in my watcher.js to disable JSHint.

``` javascript
var args = process.argv.slice(2);
var isDisableJSHint = args.indexOf("--disableJSHint") > -1; 
var _jshintCallback = function(error) {
    if (!isDisableJSHint && (!error || error.code === 0)) {
          hasJSHint = true;
    }
```

It will be great if you can accommodate the watcher for .ts file which watches for change and compiles to js and then transfer that file to device.

**Comment by NathanaelA** [comment]
Actually you might be able to leave jshint running so you get the checks it does.   However I'm going to guess typescript during the compiling probably catches several of the issues that jshint would complain about.   The main .jshintrc file that greys put in your main folder had the jshint configuration.   One of my default checks is probably to strict for ts generated code.  If you have a sample ts file that fails jshint i can look at it and tell you which rule to disable/enable.

**Comment by NathanaelA** [comment]
When you run the gulp task where does it put the js files? In the same folder as the ts files?

**Comment by shripalsoni04** [comment]
I checked the generated code from typescript. Actually the issue is whenever we extend a class in typescript like

`export class A extends B`

it will create __extends function like

``` javascript
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    __.prototype = b.prototype;
    d.prototype = new __();
};
```

And this code was not compliant with the jshint rules. So  I have updated the.jshintrc file and now its working fine.

This is my updated .jshintrc file

``` javascript
{
  "undef": true,
  "nonew": true,
  "curly": false,
  "noarg": true,
  "forin": true,
  "noempty": true,
  "eqeqeq": true,
  "strict": false,
  "bitwise": true,
  "newcap": false,
  "camelcase": true,
  "browser": true,
  "node": true,
  "shadow": true,
  "predef": [ "android", "java", "javax" ]
}
```

Currently, I have configured the project to put the generated js files in the same folder as of ts files.

Thanks for your help and  :+1:  for this very helpful plugin.

**Comment by NathanaelA** [comment]
LiveEdit now has first class TS support.  ;-)
