### ISSUE TITLE
adb permission denied

### ISSUE THREAD

**Issue by pokleh** [NathanaelA/nativescript-liveedit#6]
Hi,

I am using Samsung Galaxy Mega (GT-I9205) and android version 4.2.2.
When I save my file, nothing happen on my device screen.
This is log on the watcher screen.

Checking updated file:  ./app/app.css
Pushed to Device:  ./app/app.css
{ [Error: Command failed: C:\Windows\system32\cmd.exe /s /c "adb push "./app/app.css" /data/data/org.nativescript.test/files/./app/app.css"
failed to copy './app/app.css' to '/data/data/org.nativescript.test/files/./app/app.css': Permission denied
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\Windows\system32\cmd.exe /s /c "adb push "./app/app.css" /data/data/org.nativescript.test/files/./app/app.css"' }

failed to copy './app/app.css' to '/data/data/org.nativescript.test/files/./app/app.css': Permission denied

**Comment by NathanaelA** [comment]
Interesting.   I'll do some research on this.   I haven't seen this myself.  But then all my work is on the emulator for the rapid development ability as geny emulator is way faster than even my s5.

**Comment by NathanaelA** [comment]
I did some research on this -- I have an idea that might fix this on non-rooted real devices.   I will be coding up secondary method to see if this will work... @pokleh would you be willing to test this once I have it done?

**Comment by pokleh** [comment]
Of couse...i'll wait for that :)

**Comment by pokleh** [comment]
hi @NathanaelA ,

I just done my testing for the fix you had done.
Here are log from the watcher console...

---

NativeScript LiveSync Watcher v0.08

## (c)2015, Master Technology.  www.master-technology.com

Watching your project: org.nativescript.test

Checking updated file:  ./app/main-page.xml
Pushed to Device:  ./app/main-page.xml /data/local/tmp/org.nativescript.test/main-page%2Exml

Checking updated file:  ./app/main-page.xml
Pushed to Device:  ./app/main-page.xml /data/local/tmp/org.nativescript.test/main-page%2Exml

Checking updated file:  ./app/main-page.xml
Pushed to Device:  ./app/main-page.xml /data/local/tmp/org.nativescript.test/main-page%2Exml

Checking updated file:  ./app/main-page.xml
Pushed to Device:  ./app/main-page.xml /data/local/tmp/org.nativescript.test/main-page%2Exml

Checking updated file:  ./app/main-page.xml
Pushed to Device:  ./app/main-page.xml /data/local/tmp/org.nativescript.test/main-page%2Exml

The device screen also work fine.

Thank you for you fast action...
