### ISSUE TITLE
Upgrade for runtime version 1.2.1

### ISSUE THREAD

**Issue by shripalsoni04** [NathanaelA/nativescript-liveedit#7]
On creating new project from nativescript CLI and then on adding nativescript-livesync plugin, it is giving below message:

"This version of LiveSync does not support the version of the Android runtimes you have.
 This is probably because you have updated to a newer version of the NativeScript Android runtimes.
 A new version of NativeScript-LiveSync should be released shortly."

Current version of nativescript android runtime is 1.2.1. 

Can you provide the patched runtime for version 1.2.1.

**Comment by NathanaelA** [comment]
Thanks for letting me know.  I was driving cross country and just got my internet back today.   I'll get a new version pushed later today once I get my code base updated to their 1.2.1 version.

**Comment by NathanaelA** [comment]
I've pushed a new version for the v1.2.1 runtimes.  Thanks for letting me know.   Looks like a v1.2.2 version is also coming shortly.   If they are going to be pushing more frequent updates to the runtimes I need to automate this process a bit more...   :grinning:

**Comment by shripalsoni04** [comment]
Thanks for the update. :+1:
