### ISSUE TITLE
Add link to referenced issue

### ISSUE THREAD

**Issue by vicentedealencar** [NathanaelA/nativescript-liveedit#8]
I would like to upvote the issue, but without the link this is not trivial

readme is like this now:
### Con's of Master Technology's LiveSync:
- Until Telerik accepts the patch; you have to use the included patched runtime. (Please vote up the issue!)

**Comment by NathanaelA** [comment]
Done.  I dropped the link on that line also.  (& v1.30 has been pushed today).

**Comment by vicentedealencar** [comment]
thank you
